[package]
name = "opentrace-mcp"
publish.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "MCP server for agent coordination and data routing"


[[bin]]
name = "opentrace-mcp"  
path = "src/bin/opentrace.rs"

[dependencies]
opentrace-bpf = {workspace = true}
opentrace-kit = {workspace = true}
thiserror = { workspace = true } 
serde = {workspace = true}
clap = {workspace = true}
serde_json = {workspace = true}
rmcp = {workspace = true}
tokio = {workspace = true}
tokio-util = {workspace = true}
axum = {workspace = true}
