[package]
name = "opentrace-server"
publish.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Management server with Web UI for MCP servers and Agents"

[[bin]]
name = "opentrace-server"  
path = "src/bin/opentrace.rs"

[dependencies]
opentrace-kit = {workspace = true}

thiserror = { workspace = true }
tokio = {workspace = true}

[lints]
workspace = true
