[package]
name = "opentrace-server"
version = "0.1.0"
edition = "2024"

[lib]
name = "opentrace_server"  
path = "src/lib.rs"          
crate-type = ["lib"]        

[dependencies]
opentrace-bpf = {workspace = true}

libc = { workspace = true } 
clap = {workspace = true}
thiserror = { workspace = true } 
tokio = {workspace = true}
axum = {workspace = true}
axum-server = {workspace = true}
