[package]
name = "opentrace-agent"
publish.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Agent service exposing eBPF metrics/events as Prometheus endpoints"

[[bin]]
name = "opentrace-agent"  
path = "src/bin/opentrace.rs"

[dependencies]

[lints]
workspace = true
