[package]
name = "opentrace-agent"
publish.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Agent service exposing eBPF metrics/events as Prometheus endpoints"

[[bin]]
name = "opentrace-agent"  
path = "src/bin/opentrace.rs"

[dependencies]
opentrace-bpf = {workspace = true}
opentrace-kit = {workspace = true}
tokio = {workspace = true}
tokio-util = {workspace = true}
thiserror = { workspace = true }
axum = { workspace = true }
prometheus = {workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
