[package]
name = "opentrace-codegen"
publish.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Code generation for templates and scaffolding"

[[bin]]
name = "opentrace-codegen"  
path = "src/bin/opentrace.rs"

[dependencies]

[lints]
workspace = true
